CREATE TABLE IF NOT EXISTS users (id BIGSERIAL NOT NULL PRIMARY KEY, nama VARCHAR(50) NOT NULL, email VARCHAR(100) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE);
CREATE TABLE IF NOT EXISTS comments (id BIGSERIAL NOT NULL PRIMARY KEY, user_id BIGINT NOT NULL, nama VARCHAR(255) NOT NULL, hadir BOOLEAN NOT NULL DEFAULT false, komentar TEXT , CONSTRAINT FK_comments_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE);
ALTER TABLE comments ADD uuid VARCHAR(255)  UNIQUE;
ALTER TABLE comments ADD ip VARCHAR(255) , ADD user_agent TEXT ;
ALTER TABLE comments ADD parent_id VARCHAR(255) , ADD CONSTRAINT FK_comments_parent_id FOREIGN KEY(parent_id) REFERENCES comments(uuid) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS likes (id BIGSERIAL NOT NULL PRIMARY KEY, uuid VARCHAR(255) NOT NULL, comment_id VARCHAR(255) NOT NULL, CONSTRAINT FK_likes_comment_id FOREIGN KEY(comment_id) REFERENCES comments(uuid) ON DELETE CASCADE, created_at TIMESTAMP WITHOUT TIME ZONE, updated_at TIMESTAMP WITHOUT TIME ZONE);
ALTER TABLE comments ADD own VARCHAR(255)  UNIQUE;
ALTER TABLE likes ADD user_id BIGINT , ADD CONSTRAINT FK_likes_user_id FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE;